name: Render Deploy

on:
  push:
    branches: [ main, master ] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        env:
          RENDER_URL: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          if [ -z "$env:RENDER_URL" ]; then
            echo "Erro: A variável RENDER_URL está vazia. Verifique os Secrets do GitHub."
            exit 1
          fi
          curl -f "$env:RENDER_URL"